### Build settings ###

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

### Site metadata ###

title: CSS Frameworks Demo

baseurl: "/css-frameworks-demo"
url: ""

exclude:
  - vendor/
  - LICENSE
  - README.md
